YELP_API_KEY = 'nR_G8sS8i52mlO0F1yukQQ2_mfcRY28ORAfg-At9MvuutRNGgqc0rZgXsbqsw7V3y-zR_eFRlVdRvVy-YhXi34p5fA63tPCfcKyFf1CJ_yV5Y4B-VcbgGNK-OC97W3Yx'
YELP_CLIENT_ID = 'Oec-VeCoEusUNOeZDOItCA'
OPEN_TABLE = '';

STRIPE_API_KEY = 'pk_test_ROdkyhs5rFVG8xeBkE0X66QJ';
STRIPE_SECRET_KEY = 'sk_test_yqmSap4p2Rg5ZKqCukYRMwVq'

PAYPAL_CLIENT_ID = 'AdgmKNuKKp1LKF5B88yunNc0yBoYgMoNYyyp8BS-MkYF0axvnbo5NuASfMD18lW4ix0gdwYLRn9rutLq'
PAYPAL_ACCOUNT = 'sungrass.bakery-facilitator@gmail.com'
PAYPAL_KEY = 'EBBNFHFpAzGGbI3h92Brj6UJuRBPCzdXt9inmHt8vCrOyQ_Y4vf7OrPLY_wDI1EjjXtOnuAXqpNmbwwd'